using System.Collections.Generic;
using HenhoOnline.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace HenhoOnline.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<HenhoOnline.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            AutomaticMigrationDataLossAllowed = true;
            ContextKey = "HenhoOnline.Models.ApplicationDbContext";
        }

        protected override void Seed(HenhoOnline.Models.ApplicationDbContext context)
        {

            context.Database.ExecuteSqlCommand("DBCC CHECKIDENT('dbo.Horoscopes', RESEED, 0)");
            context.Horoscopes.AddOrUpdate(x => x.Id,
                new Horoscope() { Id = 1, StartDate = DateTime.Parse("1990/01/27"), EndDate = DateTime.Parse("1991/02/14"), NegativeAge = "Canh Ngọ", FiveElements = "Thủy", HoroscopeMatch = "28,29", Gender = 1 },
                new Horoscope() { Id = 2, StartDate = DateTime.Parse("1991/02/15"), EndDate = DateTime.Parse("1992/02/02"), NegativeAge = "Tận Mùi", FiveElements = "Hỏa", HoroscopeMatch = "21,24,27", Gender = 1 },
                new Horoscope() { Id = 3, StartDate = DateTime.Parse("1992/02/04"), EndDate = DateTime.Parse("1993/01/22"), NegativeAge = "Nhâm Thân",FiveElements = "Thổ", HoroscopeMatch = "37,32", Gender = 1 },
                new Horoscope() { Id = 4, StartDate = DateTime.Parse("1993/01/23"), EndDate = DateTime.Parse("1994/02/09"), NegativeAge = "Quý Dậu", FiveElements = "Kim", HoroscopeMatch = "24,26,30", Gender = 1 },
                new Horoscope() { Id = 5, StartDate = DateTime.Parse("1994/02/10"), EndDate = DateTime.Parse("1995/01/30"), NegativeAge = "Giáp Tuất", FiveElements = "Kim", HoroscopeMatch = "27,29,33", Gender = 1 },
                new Horoscope() { Id = 6, StartDate = DateTime.Parse("1995/02/01"), EndDate = DateTime.Parse("1996/02/18"), NegativeAge = "Ất Hợi", FiveElements = "Thổ", HoroscopeMatch = "28,25", Gender = 1 },
                new Horoscope() { Id = 7, StartDate = DateTime.Parse("1996/02/19"), EndDate = DateTime.Parse("1997/02/06"), NegativeAge = "Bính Tý", FiveElements = "Mộc", HoroscopeMatch = "27,36", Gender = 1 },
                new Horoscope() { Id = 8, StartDate = DateTime.Parse("1997/02/07"), EndDate = DateTime.Parse("1998/01/27"), NegativeAge = "Đinh Sửu", FiveElements = "Mộc", HoroscopeMatch = "38", Gender = 1 },
                new Horoscope() { Id = 9, StartDate = DateTime.Parse("1998/01/28"), EndDate = DateTime.Parse("1999/02/15"), NegativeAge = "Mậu Dần", FiveElements = "Thổ", HoroscopeMatch = "40", Gender = 1 },
                new Horoscope() { Id = 10, StartDate = DateTime.Parse("1999/02/16"), EndDate = DateTime.Parse("2000/02/04"), NegativeAge = "Kỷ Mão", FiveElements = "Thủy", HoroscopeMatch = "29,32,33,40", Gender = 1 },
                new Horoscope() { Id = 11, StartDate = DateTime.Parse("2000/02/05"), EndDate = DateTime.Parse("2001/01/23"), NegativeAge = "Canh Thìn", FiveElements = "Hỏa", HoroscopeMatch = "31", Gender = 1 },
                new Horoscope() { Id = 12, StartDate = DateTime.Parse("2001/01/24"), EndDate = DateTime.Parse("2002/02/11"), NegativeAge = "Tân Tỵ", FiveElements = "Thổ", HoroscopeMatch = "32,38,39", Gender = 1 },
                new Horoscope() { Id = 13, StartDate = DateTime.Parse("2002/02/12"), EndDate = DateTime.Parse("2003/01/31"), NegativeAge = "Nhâm Ngọ", FiveElements = "Kim", HoroscopeMatch = "37", Gender = 1 },
                new Horoscope() { Id = 14, StartDate = DateTime.Parse("2003/02/14"), EndDate = DateTime.Parse("2004/01/21"), NegativeAge = "Quý Mùi", FiveElements = "Kim", HoroscopeMatch = "34", Gender = 1 },
                new Horoscope() { Id = 15, StartDate = DateTime.Parse("2004/01/22"), EndDate = DateTime.Parse("2005/02/08"), NegativeAge = "Giáp Thân", FiveElements = "Thổ", HoroscopeMatch = "36", Gender = 1 },
                new Horoscope() { Id = 16, StartDate = DateTime.Parse("2005/02/09"), EndDate = DateTime.Parse("2006/01/28"), NegativeAge = "Ất Dậu", FiveElements = "Mộc", HoroscopeMatch = "35,36", Gender = 1 },
                new Horoscope() { Id = 17, StartDate = DateTime.Parse("2006/01/29"), EndDate = DateTime.Parse("2007/02/16"), NegativeAge = "Bính Tuất", FiveElements = "Thổ", HoroscopeMatch = "34", Gender = 1 },
                new Horoscope() { Id = 18, StartDate = DateTime.Parse("2007/02/17"), EndDate = DateTime.Parse("2008/02/06"), NegativeAge = "Đinh Hợi", FiveElements = "Thủy", HoroscopeMatch = "32", Gender = 1 },
                new Horoscope() { Id = 19, StartDate = DateTime.Parse("2008/02/07"), EndDate = DateTime.Parse("2009/01/25"), NegativeAge = "Mậu Tý", FiveElements = "Hỏa", HoroscopeMatch = "35", Gender = 1 },
                new Horoscope() { Id = 20, StartDate = DateTime.Parse("2009/01/26"), EndDate = DateTime.Parse("2010/02/13"), NegativeAge = "Kỷ Sửu", FiveElements = "Thổ", HoroscopeMatch = "38,33", Gender = 1 },
                new Horoscope() { Id = 21, StartDate = DateTime.Parse("1990/01/27"), EndDate = DateTime.Parse("1991/02/14"), NegativeAge = "Canh Ngọ", FiveElements = "Thổ", HoroscopeMatch = "5", Gender = 0 },
                new Horoscope() { Id = 22, StartDate = DateTime.Parse("1991/02/15"), EndDate = DateTime.Parse("1992/02/02"), NegativeAge = "Tận Mùi", FiveElements = "Kim", HoroscopeMatch = "4", Gender = 0 },
                new Horoscope() { Id = 23, StartDate = DateTime.Parse("1992/02/04"), EndDate = DateTime.Parse("1993/01/22"), NegativeAge = "Nhâm Thân", FiveElements = "Kim", HoroscopeMatch = "3", Gender = 0 },
                new Horoscope() { Id = 24, StartDate = DateTime.Parse("1993/01/23"), EndDate = DateTime.Parse("1994/02/09"), NegativeAge = "Quý Dậu", FiveElements = "Thổ", HoroscopeMatch = "4,6", Gender = 0 },
                new Horoscope() { Id = 25, StartDate = DateTime.Parse("1994/02/10"), EndDate = DateTime.Parse("1995/01/30"), NegativeAge = "Giáp Tuất", FiveElements = "Hỏa", HoroscopeMatch = "3,6", Gender = 0 },
                new Horoscope() { Id = 26, StartDate = DateTime.Parse("1995/02/01"), EndDate = DateTime.Parse("1996/02/18"), NegativeAge = "Ất Hợi", FiveElements = "Thủy", HoroscopeMatch = "8", Gender = 0 },
                new Horoscope() { Id = 27, StartDate = DateTime.Parse("1996/02/19"), EndDate = DateTime.Parse("1997/02/06"), NegativeAge = "Bính Tý", FiveElements = "Thổ", HoroscopeMatch = "4,7", Gender = 0 },
                new Horoscope() { Id = 28, StartDate = DateTime.Parse("1997/02/07"), EndDate = DateTime.Parse("1998/01/27"), NegativeAge = "Đinh Sửu", FiveElements = "Mộc", HoroscopeMatch = "9", Gender = 0 },
                new Horoscope() { Id = 29, StartDate = DateTime.Parse("1998/01/28"), EndDate = DateTime.Parse("1999/02/15"), NegativeAge = "Mậu Dần", FiveElements = "Mộc", HoroscopeMatch = "6", Gender = 0 },
                new Horoscope() { Id = 30, StartDate = DateTime.Parse("1999/02/16"), EndDate = DateTime.Parse("2000/02/04"), NegativeAge = "Kỷ Mão", FiveElements = "Thổ", HoroscopeMatch = "12", Gender = 0 },
                new Horoscope() { Id = 31, StartDate = DateTime.Parse("2000/02/05"), EndDate = DateTime.Parse("2001/01/23"), NegativeAge = "Canh Thìn", FiveElements = "Kim", HoroscopeMatch = "8", Gender = 0 },
                new Horoscope() { Id = 32, StartDate = DateTime.Parse("2001/01/24"), EndDate = DateTime.Parse("2002/02/11"), NegativeAge = "Tân Tỵ", FiveElements = "Kim", HoroscopeMatch = "10,12,13", Gender = 0 },
                new Horoscope() { Id = 33, StartDate = DateTime.Parse("2002/02/12"), EndDate = DateTime.Parse("2003/01/31"), NegativeAge = "Nhâm Ngọ", FiveElements = "Hỏa", HoroscopeMatch = "11", Gender = 0 },
                new Horoscope() { Id = 34, StartDate = DateTime.Parse("2003/02/14"), EndDate = DateTime.Parse("2004/01/21"), NegativeAge = "Quý Mùi", FiveElements = "Thủy", HoroscopeMatch = "10", Gender = 0 },
                new Horoscope() { Id = 35, StartDate = DateTime.Parse("2004/01/22"), EndDate = DateTime.Parse("2005/02/08"), NegativeAge = "Giáp Thân", FiveElements = "Thổ", HoroscopeMatch = "13", Gender = 0 },
                new Horoscope() { Id = 36, StartDate = DateTime.Parse("2005/02/09"), EndDate = DateTime.Parse("2006/01/28"), NegativeAge = "Ất Dậu", FiveElements = "Mộc",HoroscopeMatch = "7", Gender = 0 },
                new Horoscope() { Id = 37, StartDate = DateTime.Parse("2006/01/29"), EndDate = DateTime.Parse("2007/02/16"), NegativeAge = "Bính Tuất", FiveElements = "Mộc", HoroscopeMatch = "18", Gender = 0 },
                new Horoscope() { Id = 38, StartDate = DateTime.Parse("2007/02/17"), EndDate = DateTime.Parse("2008/02/06"), NegativeAge = "Đinh Hợi", FiveElements = "Thổ", HoroscopeMatch = "16,12", Gender = 0 },
                new Horoscope() { Id = 39, StartDate = DateTime.Parse("2008/02/07"), EndDate = DateTime.Parse("2009/01/25"), NegativeAge = "Mậu Tý", FiveElements = "Kim", HoroscopeMatch = "13,14", Gender = 0 },
                new Horoscope() { Id = 40, StartDate = DateTime.Parse("2009/01/26"), EndDate = DateTime.Parse("2010/02/13"), NegativeAge = "Kỷ Sửu", FiveElements = "Kim", HoroscopeMatch = "17", Gender = 0 }
                    );
            //context.Users.AddOrUpdate(x => x.Id,
            //    new ApplicationUser() { Id = "1", UserName = "mai1", EmailConfirmed = false, PhoneNumberConfirmed = false, TwoFactorEnabled = false, LockoutEnabled = true, AccessFailedCount = 0, FullName = "MaiNe", Gender = 1, BirthDay = DateTime.Parse("1992/05/12"), Avatar = "", Address = "Hà Nội", Character = ApplicationUser.CharacterType.Funny },
            //    new ApplicationUser() { Id = "2", UserName = "mai2", EmailConfirmed = false, PhoneNumberConfirmed = false, TwoFactorEnabled = false, LockoutEnabled = true, AccessFailedCount = 0, FullName = "MaiNe", Gender = 0, BirthDay = DateTime.Parse("1998/02/10"), Avatar = "", Address = "Hà Nội", Character = ApplicationUser.CharacterType.Funny }


            //    );
            var manager = new UserManager<ApplicationUser>(
                new UserStore<ApplicationUser>(
                    new ApplicationDbContext()));
            var listUser = new List<ApplicationUser>()
            {
                new ApplicationUser(){UserName = "t1", FullName = "Nguyễn Văn Tuấn", BirthDay = DateTime.Parse("1990/03/24"), Avatar = "https://i.pinimg.com/236x/d2/78/99/d2789942421dc67732d6ef92739c859c.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 1},
                new ApplicationUser(){UserName = "t2", FullName = "Trần Văn Tuấn", BirthDay = DateTime.Parse("1990/07/05"), Avatar = "https://kenh14cdn.com/2017/18057840-1872174336388836-1093142526760508237-n-1505389713709-1513422190216.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 1},
                new ApplicationUser(){UserName = "t3", FullName = "Nguyễn Bá Tú", BirthDay = DateTime.Parse("1990/08/08"), Avatar = "https://static2.yan.vn/YanNews/2167221/201912/tren-facebook-khong-dang-tam-anh-nao-nhung-ngoai-doi-lai-rat-dep-trai-753838f5.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 1},
                new ApplicationUser(){UserName = "t4", FullName = "Lê Thanh Nghị", BirthDay = DateTime.Parse("1991/05/09"), Avatar = "https://static2.yan.vn/YanNews/2167221/201703/20170315-123702-1a_600x750.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 2},
                new ApplicationUser(){UserName = "t5", FullName = "Nguyễn Hưu Tuân", BirthDay = DateTime.Parse("1991/08/01"), Avatar = "https://image.giaoducthoidai.vn/650/uploaded/dienns/2017_03_21/244741_jgpp.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 2},
                new ApplicationUser(){UserName = "t6", FullName = "Lê Đức Vỹ", BirthDay = DateTime.Parse("1991/12/12"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKG_-leTi-F16HNW06GgHPaSwikPqu9IIOO3SvkAMliWFHrNl32w&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 2},
                new ApplicationUser(){UserName = "t7", FullName = "Đỗ Bá Huy", BirthDay = DateTime.Parse("1992/03/28"), Avatar = "http://kenh14.vn/ban-se-tiec-hui-hui-neu-chua-biet-het-nhung-trai-dep-hot-nhat-mxh-nam-2017-vua-qua-20171216175653371.chn", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 3},
                new ApplicationUser(){UserName = "t8", FullName = "Nguyễn Hiền Tiến", BirthDay = DateTime.Parse("1992/04/13"), Avatar = "https://kenh14cdn.com/2018/5/14/screen-shot-2018-05-14-at-95026-pm-1526309638534871393209.png", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 3},
                new ApplicationUser(){UserName = "t9", FullName = "Trịnh Văn Nam", BirthDay = DateTime.Parse("1992/09/09"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFVv7vXjDBamKPmkhSxRl8GRCtq4AcuvppCBGjp-a4uy0Eg3fx&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 3},
                new ApplicationUser(){UserName = "t10", FullName = "Đỗ Văn Nam", BirthDay = DateTime.Parse("1993/05/16"), Avatar = "https://static.giaoducthoidai.vn/uploaded/yench/2016_03_20/bansebatngokhibietsuthatveanhchangdeptrainhuhanquocnay_ztwh.jpg?width=500", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 4},
                new ApplicationUser(){UserName = "t11", FullName = "Trinh Văn Bô", BirthDay = DateTime.Parse("1993/07/18"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmelXGfVDiXyRfDR3h_JFf1d9pSnKcxlkKk4mbltoCBCkGx849-A&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 4},
                new ApplicationUser(){UserName = "t12", FullName = "Lê Hữu Độ", BirthDay = DateTime.Parse("1993/10/28"), Avatar = "https://kenh14cdn.com/2017/img-7310-1506166016665-1513419731695.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 4},
                new ApplicationUser(){UserName = "t13", FullName = "Trần Văn Luân", BirthDay = DateTime.Parse("1994/04/10"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCgWdlaG6MDkvqreielL0Q4wKd8x0TYLY0J385qqCvqatGJjTU&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 5},
                new ApplicationUser(){UserName = "t14", FullName = "Đỗ Hùng Dũng", BirthDay = DateTime.Parse("1994/12/05"), Avatar = "https://znews-photo-td.zadn.vn/w660/Uploaded/ofh_fdmzsofw/2017_08_11/12919646_643885959092377_2264136901140285059_n.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 5},
                new ApplicationUser(){UserName = "t15", FullName = "Lê Đức Huy", BirthDay = DateTime.Parse("1994/10/10"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTANTWDwD2KV02J7LZuNF8k40izpxaZ4UbL88_wq7jj8GNqKNy8Kw&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 5},
                new ApplicationUser(){UserName = "t16", FullName = "Nguyễn Văn An", BirthDay = DateTime.Parse("1995/07/19"), Avatar = "https://static2.yan.vn/YanNews/2167221/202002/day-thi-dai-thanh-cong-trai-dep-be-lai-thanh-gai-xinh-gay-sot-mxh-6ae5387f.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 6},
                new ApplicationUser(){UserName = "t17", FullName = "Lê Anh Tùng", BirthDay = DateTime.Parse("1995/12/15"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU-IX7FI0LHSZhEy3vuiR-SzToLxg7LIlC3b4oFT_gJ96yIlU3&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 6},
                new ApplicationUser(){UserName = "t18", FullName = "Trần Văn Việt", BirthDay = DateTime.Parse("1995/08/17"), Avatar = "https://we25.vn/media/images/trai-hang-khong(3).jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 6},
                new ApplicationUser(){UserName = "t19", FullName = "Nguyễn Hữu Nghĩa", BirthDay = DateTime.Parse("1996/03/24"), Avatar = "https://lh5.googleusercontent.com/proxy/cr-bxxR-1e1Qlyj2ovdiV-SIbMlh01LB0hXdouk9_aJC7Z6f9kWSc9s3J-y_oky8jJQIy6zWDWGf6M28bo3KcFBwSXn8q_NlpN_KaPhLHGV6FEAyYnaSfFoZkTnRtSkJRU4rjOsrRGmYm8khEZ216f_-1BLS-pKwHoFZe6Q", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 7},
                new ApplicationUser(){UserName = "t20", FullName = "Trần Võ Đang", BirthDay = DateTime.Parse("1996/07/05"), Avatar = "https://cafefcdn.com/2018/11/21/photo-1-15427899736752072939627.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 7},
                new ApplicationUser(){UserName = "t21", FullName = "Trần Văn Trọng", BirthDay = DateTime.Parse("1996/08/08"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWYrnjMatCC0_GWUPovv4m5lrBwIMZ0pXC-Dmk1HfN3FNJLB6_&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 7},
                new ApplicationUser(){UserName = "t22", FullName = "Nguyễn Văn Trường", BirthDay = DateTime.Parse("1997/05/09"), Avatar = "https://2sao.vietnamnetjsc.vn/images/2017/04/15/15/02/bb2.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 8},
                new ApplicationUser(){UserName = "t23", FullName = "Đinh Văn Mai", BirthDay = DateTime.Parse("1997/08/01"), Avatar = "https://static2.yan.vn/YanNews/2167221/201912/cam-dong-hinh-anh-me-trai-hoa-khap-nguoi-con-trai-sau-khi-hien-tang-0aa17a24.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 8},
                new ApplicationUser(){UserName = "t24", FullName = "Trịnh Văn Nam", BirthDay = DateTime.Parse("1997/06/12"), Avatar = "https://1.bp.blogspot.com/-r6XhpUmDS58/Xh_fu91RhLI/AAAAAAAAU2I/XTDgGDfPUa0I1yFhr71TGe-s4lO_I0NYACLcBGAsYHQ/s1600/hinh-anh-trai-dep%253Ddau-nam-hot-boy-2k-Wap102%2B%252822%2529.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 8},
                new ApplicationUser(){UserName = "t25", FullName = "Lê Văn Thảo", BirthDay = DateTime.Parse("1998/03/28"), Avatar = "https://2sao.vietnamnetjsc.vn/images/2017/08/02/06/58/hot-boy-9X-3.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 9},
                new ApplicationUser(){UserName = "t26", FullName = "Trịnh Văn Xuất", BirthDay = DateTime.Parse("1998/11/13"), Avatar = "https://s1.img.yan.vn/YanNews/2167221/201604/20160419-035623-2_600x344.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 9},
                new ApplicationUser(){UserName = "t27", FullName = "Định Văn Nhất", BirthDay = DateTime.Parse("1998/09/09"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfmUOK484KMj0aFlhIg5-8Wn7oqRuQcu3bHMhJAT903RCKAoHHWQ&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 9},
                new ApplicationUser(){UserName = "t28", FullName = "An Văn Long", BirthDay = DateTime.Parse("1999/12/16"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR34ibAnrleBLm1Mbqcb8cbTI-64qTs3Ko96La4bRbv_5Yu9SAY0w&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 10},
                new ApplicationUser(){UserName = "t29", FullName = "Trinh Lê Nghi", BirthDay = DateTime.Parse("1999/07/18"), Avatar = "https://file.vforum.vn/hinh/2014/1/boy-dep-trai-32.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 10},
                new ApplicationUser(){UserName = "t30", FullName = "Đặng Hữu Đệ", BirthDay = DateTime.Parse("1999/04/28"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1Tub8knOV2YTO5EKqHyfEmrlAQprruB3uCXHse8i97w-Fqoc_&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 10},
                new ApplicationUser(){UserName = "t31", FullName = "Đỗ Đức Anh", BirthDay = DateTime.Parse("2000/08/10"), Avatar = "https://znews-photo.zadn.vn/w660/Uploaded/ofh_pgazsaff/2018_08_20/36382069_789532344768852_8850209610137600000_n.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 11},
                new ApplicationUser(){UserName = "t32", FullName = "Vương Viết Thắng", BirthDay = DateTime.Parse("2000/07/05"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvj3hMV5cKbYvn99RLGqcVAhRpetS-EyOtF5jJiCYaxrW-46X0&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 11},
                new ApplicationUser(){UserName = "t33", FullName = "Mai Nhất Tâm", BirthDay = DateTime.Parse("2000/12/10"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRU7NEeKcTaWQwxZez8-vYeHGovYN9F4Kn7_yKO7eC3pdbWK6S&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 11},
                new ApplicationUser(){UserName = "t34", FullName = "Đỗ Đức Anh", BirthDay = DateTime.Parse("2001/07/19"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2gcC1WdiJBM1kEmmHMJ2qD0YvRPuI8t7f3fKw0mZTBbhvfKmnEw&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 12},
                new ApplicationUser(){UserName = "t35", FullName = "Nguyễn Thiện Thảo", BirthDay = DateTime.Parse("2001/04/15"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfJ7Ye-2fnBZ6jnzMtWK5fN4c2Vm4oPtXr5BiXuuvE93DQcKLiFg&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 12},
                new ApplicationUser(){UserName = "t36", FullName = "Lê Văn Lương", BirthDay = DateTime.Parse("2001/08/17"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlkW_HikVmKTyjQJsSQ2Y-Gg3HxyaQyJ9KoDWK732czguyzT_lfA&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 12},
                new ApplicationUser(){UserName = "t37", FullName = "Nguyễn Viết Ái", BirthDay = DateTime.Parse("2002/03/30"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2YtyxC4tT-eKOQ1z-HFH-YWYfWfwjNOrvLrz72hPZjY4bsXttew&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 13},
                new ApplicationUser(){UserName = "t38", FullName = "Nguyễn Trọng Toàn", BirthDay = DateTime.Parse("2002/07/07"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLOW4oCPc-T-2aEp9n-3evRG_t-sOV-sBKszOwiRumcjo7UMsPfA&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 13},
                new ApplicationUser(){UserName = "t39", FullName = "Vũ Văn Đức", BirthDay = DateTime.Parse("2002/08/12"), Avatar = "https://cdn.phunuvagiadinh.vn/baongoc/thu-mon-du-bi-cua-u23-viet-nam2.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 13},
                new ApplicationUser(){UserName = "t40", FullName = "Nguyễn Việt Tiệp", BirthDay = DateTime.Parse("2003/05/30"), Avatar = "https://kenh14cdn.com/thumb_w/660/2017/2131471613739253460582874150518321823079014n-1507020328709-1513420681816.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 14},
                new ApplicationUser(){UserName = "t41", FullName = "Phạm Thanh Luân", BirthDay = DateTime.Parse("2003/08/08"), Avatar = "https://anh.24h.com.vn/upload/2-2017/images/2017-06-02/1496384862-149606178873168-photo-15-1469420131942.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 14},
                new ApplicationUser(){UserName = "t42", FullName = "Nguyễn Linh Bảo", BirthDay = DateTime.Parse("2003/12/12"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3izyXFnQ9hpPSvxGD6i2Hh1ng5KD3nk8BeoDmHygLS3D2YY_9Zw&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 14},
                new ApplicationUser(){UserName = "t43", FullName = "Phạm Văn Đức", BirthDay = DateTime.Parse("2004/03/24"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6RpbH4N7wj9zU35EYHVEAvMQFg5mxZ5m1i5pxTc0uNshmus-a&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 15},
                new ApplicationUser(){UserName = "t44", FullName = "Nguyễn Bá Vinh", BirthDay = DateTime.Parse("2004/04/13"), Avatar = "https://photo-1-baomoi.zadn.vn/w1000_r1/2017_01_29_335_21424728/4422a0ea8bab62f53bba.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 15},
                new ApplicationUser(){UserName = "t45", FullName = "Đặng Đức Cường", BirthDay = DateTime.Parse("2004/09/05"), Avatar = "https://kenh14cdn.com/thumb_w/660/2019/12/27/47-1577433421955172282655.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 15},
                new ApplicationUser(){UserName = "t46", FullName = "Định Văn Nhất", BirthDay = DateTime.Parse("2005/05/30"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXIqr4ysuh4IaFa9q_-L9gm2gvLr7-ERZ1_HnpilQ_CWWKRGra&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 16},
                new ApplicationUser(){UserName = "t47", FullName = "Hồ Sỹ Quang", BirthDay = DateTime.Parse("2005/07/18"), Avatar = "https://image.thanhnien.vn/980/uploaded/hoangnam/2017_01_24/2_gohj.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 16},
                new ApplicationUser(){UserName = "t48", FullName = "Nguyễn Xuân Tân", BirthDay = DateTime.Parse("2005/10/28"), Avatar = "https://photo-3-baomoi.zadn.vn/w1000_r1/2019_08_02_180_31693139/84da55a712e7fbb9a2f6.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 16},
                new ApplicationUser(){UserName = "t49", FullName = "Nguyễn Như Tuấn", BirthDay = DateTime.Parse("2006/04/16"), Avatar = "https://lh3.googleusercontent.com/proxy/aEvIvJinnav9vgimMS8gXIEOByQ-jSwCe-zkMOEzkX10slyHq5lMlf62bOB4SBW5PzWhlawFh8iYYbhZer8rNiHwRGpKGTHnPvuaGr8w_UMEtK8dcH6W1RlfY6GnvbuBJwJx4y39", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 17},
                new ApplicationUser(){UserName = "t50", FullName = "Bế Nọc Cương", BirthDay = DateTime.Parse("2006/12/05"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbo2miUHlA4pQ3gquB4xQ4r7DP71E1ONW5CqlgXp-8MQZWZI91&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 17},
                new ApplicationUser(){UserName = "t51", FullName = "Trần Văn Sơn", BirthDay = DateTime.Parse("2006/10/10"), Avatar = "https://quanlotnamdepblog.files.wordpress.com/2016/03/20150705110501-22.jpg?w=520&h=520&crop=1", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 17},
                new ApplicationUser(){UserName = "t52", FullName = "Nguyễn Văn Chiến", BirthDay = DateTime.Parse("2007/07/29"), Avatar = "https://kenh14cdn.com/thumb_w/600/000522cca9/2015/07/28/11800367_651442878323695_2439043554607682663_n-ff816.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 18},
                new ApplicationUser(){UserName = "t53", FullName = "Trần Tuấn Anh", BirthDay = DateTime.Parse("2007/12/15"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaMbjeA4a62ZFzx_FK6RWKcc5SicyFUSZnqCJX7I8fATKYlX1S&s", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 18},
                new ApplicationUser(){UserName = "t54", FullName = "Mai Xuan Dũng", BirthDay = DateTime.Parse("2007/08/11"), Avatar = "https://cdn.pose.com.vn/legacy/images/baiviet/201507/10514642_10202436547667236_8671669448747587993_n-288fd.jpg	", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 18},
                new ApplicationUser(){UserName = "t55", FullName = "Đặng Đức Nam", BirthDay = DateTime.Parse("2008/03/24"), Avatar = "https://nld.mediacdn.vn/thumb_w/540/2016/vtv-awards-kang-tae-oh-ap-dao-binh-chon-hang-muc-dien-vien-nam-an-tuong-1482912138095.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 19},
                new ApplicationUser(){UserName = "t56", FullName = "Nguyễn Văn Tùng", BirthDay = DateTime.Parse("2008/07/05"), Avatar = "https://sohanews.sohacdn.com/k:2015/6-10173789-10201881216504304-6205307536044402783-n-5b909-1435909241967/dien-dao-truoc-ve-dep-trai-cua-co-truong-tre-nhat-viet-nam.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 19},
                new ApplicationUser(){UserName = "t57", FullName = "Lê Hữu Quyền", BirthDay = DateTime.Parse("2008/08/17"), Avatar = "https://media.tinmoi.vn/2014/11/27/Kenny-Sang-4.jpg", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 19},
                new ApplicationUser(){UserName = "t58", FullName = "Nguyễn Hữu Tú", BirthDay = DateTime.Parse("2009/05/09"), Avatar = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4DM8POvKESlP9ivJv1inHqRwaO90O-HEtuMbxMMybhuh4ECEb&s", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 20},
                new ApplicationUser(){UserName = "t59", FullName = "Nguyễn Tuấn Dũng", BirthDay = DateTime.Parse("2009/08/30"), Avatar = "https://lh6.googleusercontent.com/proxy/yqpH8NA2QyOPWxEp5rjW9hmVgr7VDQErUl0lEjVs8t0UTU3Yqvd5I3Iylg2I7-A0n7ezB3a8NXeQrb4fOqcehTON3FhJ1UCITuWQTc-EA1RBbby4320r-2bo45jjqPplTv3EP4ttOtgwvnUm8zmRhx4i7GavIw	", Gender = 1, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 20},
                new ApplicationUser(){UserName = "t60", FullName = "Lê Hữu Tú", BirthDay = DateTime.Parse("2009/06/12"), Avatar = "https://2sao.vietnamnetjsc.vn/2015/09/20/16/57/13.jpg", Gender = 0, Character = ApplicationUser.CharacterType.Funny, Address = "khong can dien vao", HoroscopeId = 20},

            };
            foreach (var user in listUser)
            {
                manager.Create(user, "password");
            }
        }
    }
}
